numpy.random is a feature of the NumPy package in Python. It produces random samples of data using Bitgenerator and Generator to create samples from various statistical distributions. It can produce the below types of data-

## Simple Random Data
This include generating and returning random floats, integers shapes bytes and 1-D arrays. The type of data used is determined by the ending. The following are avaiable with examples shown below bolded-
<br>**rand(d0, d1, …, dn)**
<br>randn(d0, d1, …, dn)
<br>**randint(low[,high, size, dtype])**
<br>random_integers(low[, high, size])
<br>random_sample([size])
<br>random([size])
<br>ranf([size])
<br>**sample([size])**
<br>choice(a[, size, replace, p])
<br>bytes(length)

In [38]:
import numpy

numpy.random.rand(3,4)

array([[0.23698733, 0.7703989 , 0.85195923, 0.59148674],
       [0.21872512, 0.16767854, 0.70754265, 0.04237337],
       [0.67556447, 0.59907018, 0.62834896, 0.74564573]])

This function returns random floats from a uniform distribution of (0,1) in the shape of an array in the arrangement of the contents of the paranthesis in the form of numpy.random.rand(d0,d1,...,dn) where d$_{i}$ in the paranthesis is optional but if entered must be positive integers. If no argument is presented within the paranthesis a single float is returned.

If in place of rand we used randn then the returned values within the array would be a random normal distribution filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1.


***

In [28]:
numpy.random.randint(3,24,size=(3,2),dtype=int)

array([[ 4,  9],
       [19, 18],
       [ 3, 20]])

The above function does

***

In [26]:
numpy.random.sample(10)

array([0.82064055, 0.73100651, 0.17003771, 0.44110701, 0.98541602,
       0.9013557 , 0.48392954, 0.9027864 , 0.60609817, 0.31673823])

The above function does

***

## Permutations 
Either randomly shuffle an existing sequence or generate and return a permutated sequence. The following are avaiable-
<br> shuffle(x)	
**permutation(x)**	

In [29]:
numpy.random.permutation([7, 54, 36, 98, 45, 63, 61])

array([61,  7, 45, 98, 36, 63, 54])

The above function does

***

## Distributions
This can draw samples from a number of different distributions. The following are avaiable-
<br>beta(a, b[, size])
<br>**binomial(n, p[, size])**
<br>chisquare(df[, size])
<br>dirichlet(alpha[, size])
<br>exponential([scale, size])
<br>f(dfnum, dfden[, size])
<br>gamma(shape[, scale, size])
<br>geometric(p[, size])
<br>gumbel([loc, scale, size])
<br>hypergeometric(ngood, nbad, nsample[, size])
<br>laplace([loc, scale, size])
<br>logistic([loc, scale, size])
<br>**lognormal([mean, sigma, size])**
<br>logseries(p[, size])
<br>multinomial(n, pvals[, size])
<br>multivariate_normal(mean, cov[, size, …)
<br>negative_binomial(n, p[, size])
<br>noncentral_chisquare(df, nonc[, size])
<br>noncentral_f(dfnum, dfden, nonc[, size])
<br>normal([loc, scale, size])
<br>pareto(a[, size])
<br>poisson([lam, size])
<br>power(a[, size])
<br>rayleigh([scale, size])
<br>standard_cauchy([size])
<br>**standard_exponential([size])**
<br>standard_gamma(shape[, size])
<br>standard_normal([size])
<br>standard_t(df[, size])
<br>triangular(left, mode, right[, size])
<br>uniform([low, high, size])
<br>vonmises(mu, kappa[, size])
<br>wald(mean, scale[, size])
<br>weibull(a[, size])
<br>zipf(a[, size])

In [42]:
numpy.random.binomial(100, 0.25, 50)

array([25, 31, 16, 28, 24, 28, 24, 21, 26, 21, 22, 30, 20, 24, 28, 23, 17,
       18, 24, 30, 25, 20, 29, 26, 18, 25, 27, 27, 23, 24, 28, 26, 24, 17,
       28, 26, 25, 29, 26, 28, 24, 29, 29, 24, 24, 20, 29, 23, 31, 31])

The above function does

***

In [41]:
numpy.random.lognormal(3, 1, 50)

array([ 49.7386227 ,  18.8643931 ,  30.36262294,  11.37367929,
        38.94332683,  12.01598367,  33.50998612,  13.00499127,
         4.37493145,  27.02448768,  79.05563518,   2.73878774,
        25.4220955 ,  13.06825306,  39.20266688,  16.61151913,
        20.48009725,  12.59611463,   9.36110713,  66.9477224 ,
        15.35115379,   5.6031321 ,  11.2564311 ,   9.05650141,
        37.12300721, 135.46160281,  30.62452943,  51.14952523,
        67.46404228,  49.91938773,   6.0858647 ,  66.85780215,
        39.85682295,  14.76553963, 304.77518898,   8.81299373,
        40.8665305 ,  17.75591165,  14.84347962,  69.61803605,
        17.72712656,  84.17507494, 119.3344717 ,   7.35051037,
        12.23047845,   3.99963496,  25.81140078,   3.90413376,
         7.49070708,   5.54193031])

The above function does

***

In [40]:
numpy.random.standard_exponential(50)

array([0.36277995, 0.50192331, 0.47681244, 0.80906633, 0.51895371,
       0.40852097, 0.56768805, 2.75136479, 0.37048821, 0.37544587,
       0.55989792, 0.9796266 , 1.76733036, 0.58139068, 0.14833886,
       1.17777371, 1.12057983, 2.18394923, 0.09468357, 2.32405204,
       1.45488369, 3.73984079, 0.16287665, 0.14995288, 0.23353383,
       0.14563703, 0.29921126, 0.11331626, 1.39712599, 1.15699793,
       0.67171291, 1.25469757, 0.48396564, 0.2627635 , 0.02136193,
       1.1525083 , 2.24303313, 0.35510954, 1.28166411, 1.11569733,
       1.10227551, 1.88997267, 0.51986006, 1.26148478, 1.79777192,
       2.95862458, 0.14706007, 0.96986853, 0.3941494 , 0.04486154])

The above function does

***

## Random Generator
This is a container for the Mersenne Twister pseudo-random number generator. The following are avaiable-
<br>**RandomState([seed])**
<br>seed([seed])
<br>get_state()
<br>set_state(state)

In [11]:
numpy.random.RandomState(seed=50)

Source: https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html Accessed 22/10/19
https://www.ibm.com/support/knowledgecenter/en/SSGNPV_1.1.3/dsx/markd-jupyter.html Accessed 22/10/19